wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/training/BloomRXN/ECFewShotTraining/train.py
    python_version: 3.9.18
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.43.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1745629679
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 49
      - 53
      - 55
      - 77
      - 103
      2:
      - 1
      - 5
      - 9
      - 11
      - 49
      - 53
      - 55
      - 77
      - 103
      3:
      - 7
      - 13
      - 23
      - 66
      4: 3.9.18
      5: 0.17.5
      6: 4.43.4
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss_step
      5: 1
      6:
      - 1
    - 1: ec1___a_train_accuracy_step
      5: 1
      6:
      - 1
    - 1: ec1___a_train_f1score_step
      5: 1
      6:
      - 1
    - 1: ec1___a_train_precision_step
      5: 1
      6:
      - 1
    - 1: ec1___a_train_recall_step
      5: 1
      6:
      - 1
    - 1: ec1___b_train_accuracy_step
      5: 1
      6:
      - 1
    - 1: ec1___b_train_f1score_step
      5: 1
      6:
      - 1
    - 1: ec1___b_train_precision_step
      5: 1
      6:
      - 1
    - 1: ec1___b_train_recall_step
      5: 1
      6:
      - 1
    - 1: ec2___a_train_accuracy_step
      5: 1
      6:
      - 1
    - 1: ec2___a_train_f1score_step
      5: 1
      6:
      - 1
    - 1: ec2___a_train_precision_step
      5: 1
      6:
      - 1
    - 1: ec2___a_train_recall_step
      5: 1
      6:
      - 1
    - 1: ec2___b_train_accuracy_step
      5: 1
      6:
      - 1
    - 1: ec2___b_train_f1score_step
      5: 1
      6:
      - 1
    - 1: ec2___b_train_precision_step
      5: 1
      6:
      - 1
    - 1: ec2___b_train_recall_step
      5: 1
      6:
      - 1
    - 1: ec3___a_train_accuracy_step
      5: 1
      6:
      - 1
    - 1: ec3___a_train_f1score_step
      5: 1
      6:
      - 1
    - 1: ec3___a_train_precision_step
      5: 1
      6:
      - 1
    - 1: ec3___a_train_recall_step
      5: 1
      6:
      - 1
    - 1: ec3___b_train_accuracy_step
      5: 1
      6:
      - 1
    - 1: ec3___b_train_f1score_step
      5: 1
      6:
      - 1
    - 1: ec3___b_train_precision_step
      5: 1
      6:
      - 1
    - 1: ec3___b_train_recall_step
      5: 1
      6:
      - 1
    - 1: pair_match___a___b_train_accuracy_step
      5: 1
      6:
      - 1
    - 1: pair_match___a___b_train_f1score_step
      5: 1
      6:
      - 1
    - 1: pair_match___a___b_train_precision_step
      5: 1
      6:
      - 1
    - 1: pair_match___a___b_train_recall_step
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
